[package]
name = "dao-calendar"
authors = []
description = "On-chain calendar module for DAOs. Manages events and groups with time-based scheduling and gauge integrations."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []
interface = ["dep:cw-orch"]

[dependencies]
cw-orch = { workspace = true, optional = true }
cosmwasm-std = { workspace = true }
cw721 = { workspace = true }
cw-utils = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw-ownable = { workspace = true }
dao-voting = { workspace = true }
cw-hooks = { workspace = true }
dao-dao-macros = { workspace = true }
dao-interface = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
cw721-nips = { workspace = true, default-features = false }
sha2 = "0.10"
hex = "0.4"

[dev-dependencies]
cw-multi-test = { workspace = true }
dao-testing = { workspace = true }
